apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  generation: 1
  name: podia.podium.com
spec:
  conversion:
    strategy: None
  group: podium.com
  names:
    kind: Podium
    listKind: PodiumList
    plural: podia
    singular: podium
  preserveUnknownFields: true
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
